name: publish

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com
          scope: '@fastcampus'
      - run: npm ci
      - run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_NPM_TOKEN }}
